version: "3"

services:
  particld:
      restart: unless-stopped
      container_name: btcpayserver_particld
      image: spazzymoto/particl:0.18.0.6rc1
      environment:
        PARTICL_NETWORK: ${NBITCOIN_NETWORK:-regtest}
        PARTICL_EXTRA_ARGS: |
          rpcbind=particld
          rpcport=43782
          port=51738
          whitelist=0.0.0.0/0
      expose:
        - "43782"
        - "51738"
      volumes:
        - "particl_datadir:/data"
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "part"
        NBXPLORER_PARTRPCURL: http://particld:43782/
        NBXPLORER_PARTNODEENDPOINT: particld:51738
      volumes:
        - "particl_datadir:/root/.particl"
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "part"
        BTCPAY_PARTEXPLORERURL: http://nbxplorer:32838/
volumes:
  particl_datadir: